config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "application#root_redirect"
  # TODO: ADD SHOW ROUTE WHEN READY FOR SCREENCAP CHALLENGE
  resources :malontines
  resources :users, only: [:new, :create, :show]
  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: "logout"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/love_note.rb
class LoveNote < ApplicationRecord
  validates_presence_of :message
  validates_uniqueness_of :message
  has_many :malontines
  has_many :users, through: :malontines, source: :creator
  has_many :malones, through: :malontines
end

app/models/malone.rb
class Malone < ApplicationRecord
  validates_presence_of :name, :image_url, :description
  validates_uniqueness_of :name, :image_url
  has_many :malontines
  has_many :users, through: :malontines, source: :creator
  has_many :love_notes, through: :malontines
end

app/models/malontine.rb
class Malontine < ApplicationRecord
  validates_presence_of :title, :creator_id, :malone_id, :love_note_id
  validates_uniqueness_of :title
  # TODO: error message "Sorry, you've already created that combination before!"
  validates_uniqueness_of :malone_id, scope: [:love_note_id, :creator_id]
  belongs_to :creator, class_name: :User, optional: false
  belongs_to :malone
  belongs_to :love_note
  paginates_per 20

  def love_note_message
    self.love_note.message if self.love_note
  end

  def love_note_message=(message)
    if message && message.length > 0
      candy_style = message.upcase
      self.love_note = LoveNote.find_or_create_by(message: candy_style)
    end
  end

  def self.reverse_chrono_paginated(page)
    self.order('created_at DESC').page(page)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_presence_of :username
  validates_uniqueness_of :username

  has_many :malontines, foreign_key: :creator_id
  has_many :malones, through: :malontines
  has_many :love_notes, through: :malontines

  def same_as?(user)
    self.id == user.id
  end

  def nav_title
    "#{username.titleize} ❤️'s Malontines!"
  end

  def ordered_malontines
    malontines.order("created_at DESC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def root_redirect
    redirect_to malontines_path
  end
end

app/controllers/love_notes_controller.rb
class LoveNotesController < ApplicationController
end

app/controllers/malones_controller.rb
class MalonesController < ApplicationController
end

app/controllers/malontines_controller.rb
class MalontinesController < ApplicationController
  include SessionsHelper
  before_action :authorize!, except: [:index, :show]
  before_action :find_malontine, only: [:show, :destroy, :edit]
  before_action :get_malones_and_notes, only: [:new, :edit]

  def index
    @malontines = Malontine.reverse_chrono_paginated(params[:page])
  end

  def new
    @malontine = Malontine.new
  end

  def create
    malontine = Malontine.new(malontine_params.merge({creator: current_user}))
    malontine.love_note_message = params[:malontine][:love_note_message]

    if malontine.save
      redirect_to malontines_path
    else
      flash[:errors] = malontine.errors.full_messages
      redirect_to new_malontine_path
    end
  end

  def show

  end

  def edit
    @malones = Malone.all
  end

  def destroy
    @malontine.destroy
    redirect_to malontines_path
  end

  private

  def find_malontine
    @malontine = Malontine.find(params[:id])
  end

  def get_malones_and_notes
    @malones = Malone.all
    # Add blank love note at beginning for a user to select an empty one
    @love_notes = LoveNote.order(:message).to_a.unshift(LoveNote.new)
  end

  def malontine_params
    # Strong params for Malontine
    params.require(:malontine).permit(:love_note_id, :malone_id, :title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # Login Form
  def new

  end

  # Completing Login
  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user
    else
      flash[:message] = "Invalid credentials"
      redirect_to login_path
    end
  end

  # Logout
  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to user
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def show
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/love_notes_helper.rb
module LoveNotesHelper
end

app/helpers/malones_helper.rb
module MalonesHelper
  def svg(name)
    file_path = "#{Rails.root}/app/assets/images/#{name}"
    p file_path
    return File.read(file_path).html_safe if File.exists?(file_path)
    '(not found)'
  end

  def random_pastel
    ["flamingo", "sky", "purps", "grassy", "salmon"].sample
  end
end

app/helpers/malontines_helper.rb
module MalontinesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def logged_in?
    !!current_user
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def authorize!
    flash[:auth_redirect_msg] = "Sorry, you have to be logged in to do that!"
    redirect_to login_path unless logged_in?
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def same_users?(first, second)
    first.id == second.id
  end
end

app/views/layouts/_errors.html.erb
<% if errors %>
  <div class="errors mb-4">
    <h3>Welp. That didn't work. Here's why:</h3>
    <% errors.each do |error| %>
      <p class="error mb-0"><%= error %></p>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default fixed-top bg-light border-bottom border-primary mb-1">
  <% if current_user %>
    <%= link_to current_user.nav_title, root_path %>
  <% else %>
    <%= link_to "😍 Malontines 😍", root_path %>
  <% end %>
  <form class="form-inline">
    <%= link_to "Post one", new_malontine_path, class: "btn btn-outline-secondary mr-1" %>
    <% if logged_in? %>
      <%= link_to "Log out", logout_path, method: :delete, class: "btn btn-outline-primary" %>
    <% else %>
      <%= link_to "Log in", login_path, class: "btn btn-outline-primary" %>
    <% end %>
  </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Happy Malontines</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c:800&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('post-icon.png') %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="app-container mt-3 pt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/malontines/_form.html.erb
<%= render "layouts/errors", errors: flash[:errors] %>

<%= form_for malontine do |f| %>
  <p>
    <%= f.label :title, "Title:" %>
    <%= f.text_field :title, class: "form-control" %>
  </p>
  <p>
    <%= f.label :love_note_message, "Add a love note:" %>
    <%= f.text_field :love_note_message, maxlength: 15, class: "form-control" %>
  </p>
  <p>
    <%= f.label :love_note_id, "...or choose one:" %>
    <%= f.collection_select :love_note_id, love_notes, :id, :message, class: "form-control" %>
  </p>
  <p>
    <%= f.label :malone_id, "Photo:" %>
    <%= f.collection_select :malone_id, malones, :id, :name, class: "form-control" %>
  </p>

    <%= f.submit "Post Malontine", class: "btn btn-outline-primary" %>
<% end %>

<br>

app/views/malontines/_list_item.html.erb
<li class="malontine-in-list">
  <div class="single-malone">
    <%= link_to svg(malontine.malone.svg_url), malontine %>
    <a
      class="in-heart-link"
      href="<%= malontine_path(malontine) %>">
      <h1
        class="love-note-overlay-<%= malontine.malone.note_position %> color-<%= random_pastel %>">
        <%= malontine.love_note_message %>
      </h1>
    </a>
    <h3 class="malontine-creator">(created by <%= malontine.creator.username %>)</h3>
  </div>
</li>

app/views/malontines/_pagination.html.erb
<div class="container pagination justify-content-center" >
  <%= paginate @malontines %>
</div>

app/views/malontines/edit.html.erb
<h1 class="mb-2">Change it Up</h1>

<%= render "form", malontine: @malontine, malones: @malones, love_notes: @love_notes %>

app/views/malontines/index.erb
<h1 class="large-title">Malontines</h1>

<div class="malontines-container">
  <ul class="malontines-list">
    <% @malontines.each do |malontine| %>
      <%= render "list_item", malontine: malontine %>
    <% end %>
  </ul>
</div>

app/views/malontines/index.html.erb
<div class="malontines-container">
  <%= render "pagination" %>
  <ul class="malontines-list">
    <% @malontines.each do |malontine| %>
      <%= render "list_item", malontine: malontine %>
    <% end %>
  </ul>
  <%= render "pagination" %>
</div>
<footer class="footer color-sky">app by dukegreene. heart svg by agone, used under creative commons license.</footer>

app/views/malontines/new.html.erb
<h1 class="mb-4">Spread Love!</h1>

<%= render "form", malontine: @malontine, malones: @malones, love_notes: @love_notes %>

<%= link_to "Back Home", malontines_path %>

app/views/malontines/show.html.erb
<h1><%= @malontine.title %></h1>

<div class="single-malone">
  <%= link_to svg(@malontine.malone.svg_url), @malontine %>
  <a class="in-heart-link" href="<%= malontine_path(@malontine) %>"><h1 class="love-note-overlay-<%= @malontine.malone.note_position %> color-<%= random_pastel %>"><%= @malontine.love_note_message %></h1></a>
  <h3 class="malontine-creator">(created by <%= @malontine.creator.username %>)</h3>
</div>

<% if logged_in? && current_user.same_as?(@malontine.creator) %>
  <p><%= link_to "Edit This 👨🏽‍🌾", edit_malontine_path %></p>
  <p><%= link_to "Delete This 😱", malontine_path, method: :delete %></p>
<% end %>

<p><%= link_to "Back", malontines_path %></p>

<footer class="footer color-sky">app by dukegreene. heart svg by agone, used under creative commons license.</footer>

app/views/users/new.html.erb
<h1 class="mb-4">Sign Up!</h1>

<%= render "layouts/errors", errors: flash[:errors] %>

<%= form_for @user, class: "mb-4" do |f| %>
  <p>
    <%= f.label :username, "Your username:" %>
    <%= f.text_field :username, class: "form-control" %>
  </p>
  <p>
    <%= f.label :password, "Your password:" %>
    <%= f.password_field :password, class: "form-control" %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password:" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </p>
  <p>
    <%= f.submit class: "btn btn-outline-primary" %>
  </p>
<% end %>

<%= link_to "Already a user? Log in!", login_path %>

app/views/users/show.html.erb
<h1 class="mb-4">
  This is <%= same_users?(@user, current_user) ? "your" : @user.username.titleize + "'s" %> profile.

  <% if same_users?(@user, current_user) %>
    <%= link_to "You can edit it.", "/users/#{@user.id}/edit" %>
  <% end %>
</h1>

<% if @user.malontines.any? %>
  <h2 class="mb-4">Created Malontines:</h2>

  <ul class="malontines-list">
    <% @user.ordered_malontines.each do |malontine| %>
      <h3><%= malontine.title %></h3>
      <%= render "malontines/list_item", malontine: malontine %>
    <% end %>
  </ul>
<% else %>
  <% if same_users?(@user, current_user) %>
    <p>...no Malontines from you just yet... <%= link_to "wanna fix that?", new_malontine_path %></p>
  <% else %>
    <p>...no Malontines from <%= @user.username.titleize %> just yet...</p>
  <% end %>
<% end %>